task:
  container:
    image: debian:latest
  install_script:
    - apt update
    - apt install -y debootstrap xz-utils
  create_script:
    - sh amd64.ubuntu.focal.sh
    - sh amd64.ubuntu.jammy.sh
  amd64.ubuntu.focal_artifacts:
    path: "build/amd64.ubuntu.focal.txz"
  amd64.ubuntu.jammy_artifacts:
    path: "build/amd64.ubuntu.jammy.txz"
