task:
  container:
    image: debian:latest
  install_script:
    - apt update
    - apt install -y debootstrap xz
  create_script:
    - sh amd64.ubuntu.focal.sh
  amd64.ubuntu.focal_artifacts:
    path: "build/amd64.ubuntu.focal.txz"